/// <reference types="@cloudflare/workers-types" />
import { createRequestHandler } from "react-router";
// @ts-expect-error - server build is generated by react-router build
import * as serverBuild from "./build/server/index.js";

const handleRequest = createRequestHandler(serverBuild);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === "/__health") {
      return new Response(
        JSON.stringify({ ok: true, name: "cumplechile", ts: new Date().toISOString() }),
        { headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } },
      );
    }

    const response = await handleRequest(request, {
      cloudflare: { env, ctx, request, cf: request.cf, caches },
    });

    const headers = new Headers(response.headers);
    if (url.pathname.startsWith("/assets/")) {
      headers.set("Cache-Control", "public, max-age=31536000, immutable");
    } else if (headers.get("Content-Type")?.includes("text/html")) {
      headers.set("Cache-Control", "public, max-age=300, s-maxage=300");
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
} satisfies ExportedHandler;
